### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Jackson8888** [Mrzhang3389/chatbot#1]
请输入你想查询的信息：成龙 和 李连杰合作过的电影有哪些？
原始句子：成龙 和 李连杰合作过的电影有哪些？
==============================HanLP分词==============================
[/w, 成/v, /w, 龙/n,  /w, 和/cc,  /w, 李/ng, /w, 连/ulian, /w, 杰/ag, /w, 合/v, /w, 作/v, /w, 过/uguo, /w, 的/ude1, /w, 电/n, /w, 影/ng, /w, 有/vyou, /w, 哪/ /w, ？/w]
----------------------------------------------------------------------
句子抽象化结果： 成  龙   和   李  连  杰  合  作  过  的  电  影  有  哪  些  ？ 
/usr/local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator GaussianNB from version 0.19.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
句子对应的索引4 模板：nm 演员列表
Traceback (most recent call last):
  File "chatbot.py", line 10, in <module>
    answers = ga.get_data(index, params)
  File "/Users/PycharmProjects/chatbot/KnowledgeGraph/get_answer.py", line 20, in get_data
    params[0])  # 演员列表
IndexError: list index out of range

**Comment by zh3389** [comment]
[/w, 成/v, /w, 龙/n, /w, 和/cc, /w, 李/ng, /w, 连/ulian, /w, 杰/ag, /w, 合/v, /w, 作/v, /w, 过/uguo, /w, 的/ude1, /w, 电/n, /w, 影/ng, /w, 有/vyou, /w, 哪/ /w, ？/w]  这个好像是分词出了问题, 然后导致问题分析模型识别为   某某电影的演员列表.   然后没有电影的词.  所以  out of range.    检查一下分词的包即可.
